// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apicontract

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CleanupHealthResponseStatus.
const (
	Degraded CleanupHealthResponseStatus = "degraded"
	Disabled CleanupHealthResponseStatus = "disabled"
	Ok       CleanupHealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the CleanupHealthResponseStatus enum.
func (e CleanupHealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Disabled:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// CheckJobAcceptedResponse defines model for CheckJobAcceptedResponse.
type CheckJobAcceptedResponse struct {
	JobId  string `json:"job_id"`
	Status string `json:"status"`
}

// CheckJobStatusResponse defines model for CheckJobStatusResponse.
type CheckJobStatusResponse struct {
	CompletedAt *time.Time     `json:"completed_at,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
	Error       *string        `json:"error,omitempty"`
	JobId       string         `json:"job_id"`
	Result      *CheckResponse `json:"result,omitempty"`
	StartedAt   *time.Time     `json:"started_at,omitempty"`
	Status      string         `json:"status"`
}

// CheckRequest defines model for CheckRequest.
type CheckRequest struct {
	Text      string   `json:"text"`
	Threshold *float32 `json:"threshold,omitempty"`
	TopK      *int     `json:"top_k,omitempty"`
}

// CheckResponse defines model for CheckResponse.
type CheckResponse struct {
	IsPlagiarism bool          `json:"is_plagiarism"`
	Matches      []MatchResult `json:"matches"`
	OverallScore float32       `json:"overall_score"`
	Threshold    float32       `json:"threshold"`
}

// CleanupHealthResponse defines model for CleanupHealthResponse.
type CleanupHealthResponse struct {
	Cleanup CleanupSnapshot             `json:"cleanup"`
	Service string                      `json:"service"`
	Status  CleanupHealthResponseStatus `json:"status"`
}

// CleanupHealthResponseStatus defines model for CleanupHealthResponse.Status.
type CleanupHealthResponseStatus string

// CleanupSnapshot defines model for CleanupSnapshot.
type CleanupSnapshot struct {
	Enabled          bool       `json:"enabled"`
	IntervalSeconds  int64      `json:"interval_seconds"`
	LastCutoffAt     *time.Time `json:"last_cutoff_at,omitempty"`
	LastDeletedCount int64      `json:"last_deleted_count"`
	LastError        *string    `json:"last_error,omitempty"`
	LastRunAt        *time.Time `json:"last_run_at,omitempty"`
	LastSuccessAt    *time.Time `json:"last_success_at,omitempty"`
	LastTrigger      *string    `json:"last_trigger,omitempty"`
	Reason           *string    `json:"reason,omitempty"`
	RetentionSeconds int64      `json:"retention_seconds"`
	TotalDeleted     int64      `json:"total_deleted"`
	TotalFailures    int64      `json:"total_failures"`
	TotalRuns        int64      `json:"total_runs"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *[]map[string]interface{} `json:"details,omitempty"`
	Error   string                    `json:"error"`
	Message string                    `json:"message"`
}

// HealthPayload defines model for HealthPayload.
type HealthPayload struct {
	EngineStatus *string `json:"engine_status,omitempty"`
	Error        *string `json:"error,omitempty"`
	Service      string  `json:"service"`
	Status       string  `json:"status"`
}

// IngestRequest defines model for IngestRequest.
type IngestRequest struct {
	DocumentId *string            `json:"document_id,omitempty"`
	Metadata   *map[string]string `json:"metadata,omitempty"`
	Source     *string            `json:"source,omitempty"`
	Text       string             `json:"text"`
}

// IngestResponse defines model for IngestResponse.
type IngestResponse struct {
	ChunkCount int    `json:"chunk_count"`
	Collection string `json:"collection"`
	DocumentId string `json:"document_id"`
}

// MatchResult defines model for MatchResult.
type MatchResult struct {
	ChunkId       string  `json:"chunk_id"`
	DocumentId    string  `json:"document_id"`
	ExactScore    float32 `json:"exact_score"`
	FinalScore    float32 `json:"final_score"`
	MatchedText   string  `json:"matched_text"`
	SemanticScore float32 `json:"semantic_score"`
	Source        *string `json:"source,omitempty"`
}

// PdfExtractResponse defines model for PdfExtractResponse.
type PdfExtractResponse struct {
	CharacterCount int    `json:"character_count"`
	Filename       string `json:"filename"`
	PageCount      int    `json:"page_count"`
	Text           string `json:"text"`
}

// GatewayExtractPdfMultipartBody defines parameters for GatewayExtractPdf.
type GatewayExtractPdfMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// GatewayExtractPdfMultipartRequestBody defines body for GatewayExtractPdf for multipart/form-data ContentType.
type GatewayExtractPdfMultipartRequestBody GatewayExtractPdfMultipartBody

// GatewayCheckJSONRequestBody defines body for GatewayCheck for application/json ContentType.
type GatewayCheckJSONRequestBody = CheckRequest

// SubmitCheckJobJSONRequestBody defines body for SubmitCheckJob for application/json ContentType.
type SubmitCheckJobJSONRequestBody = CheckRequest

// GatewayIngestJSONRequestBody defines body for GatewayIngest for application/json ContentType.
type GatewayIngestJSONRequestBody = IngestRequest
