// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apicontract

// BodyExtractPdfExtractPdfPost defines model for Body_extract_pdf_extract_pdf_post.
type BodyExtractPdfExtractPdfPost struct {
	File string `json:"file"`
}

// CheckRequest defines model for CheckRequest.
type CheckRequest struct {
	Text      string   `json:"text"`
	Threshold *float32 `json:"threshold,omitempty"`
	TopK      *int     `json:"top_k,omitempty"`
}

// CheckResponse defines model for CheckResponse.
type CheckResponse struct {
	IsPlagiarism bool          `json:"is_plagiarism"`
	Matches      []MatchResult `json:"matches"`
	OverallScore float32       `json:"overall_score"`
	Threshold    float32       `json:"threshold"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *[]map[string]interface{} `json:"details,omitempty"`
	Error   string                    `json:"error"`
	Message string                    `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// IngestRequest defines model for IngestRequest.
type IngestRequest struct {
	DocumentId *string            `json:"document_id,omitempty"`
	Metadata   *map[string]string `json:"metadata,omitempty"`
	Source     *string            `json:"source,omitempty"`
	Text       string             `json:"text"`
}

// IngestResponse defines model for IngestResponse.
type IngestResponse struct {
	ChunkCount int    `json:"chunk_count"`
	Collection string `json:"collection"`
	DocumentId string `json:"document_id"`
}

// MatchResult defines model for MatchResult.
type MatchResult struct {
	ChunkId       string  `json:"chunk_id"`
	DocumentId    string  `json:"document_id"`
	ExactScore    float32 `json:"exact_score"`
	FinalScore    float32 `json:"final_score"`
	MatchedText   string  `json:"matched_text"`
	SemanticScore float32 `json:"semantic_score"`
	Source        *string `json:"source,omitempty"`
}

// PdfExtractResponse defines model for PdfExtractResponse.
type PdfExtractResponse struct {
	CharacterCount int    `json:"character_count"`
	Filename       string `json:"filename"`
	PageCount      int    `json:"page_count"`
	Text           string `json:"text"`
}

// CheckPlagiarismCheckPostJSONRequestBody defines body for CheckPlagiarismCheckPost for application/json ContentType.
type CheckPlagiarismCheckPostJSONRequestBody = CheckRequest

// ExtractPdfExtractPdfPostMultipartRequestBody defines body for ExtractPdfExtractPdfPost for multipart/form-data ContentType.
type ExtractPdfExtractPdfPostMultipartRequestBody = BodyExtractPdfExtractPdfPost

// IngestDocumentIngestPostJSONRequestBody defines body for IngestDocumentIngestPost for application/json ContentType.
type IngestDocumentIngestPostJSONRequestBody = IngestRequest
